name: Build Go binaries

on:
  push:
    # We want to run the workflow on all branches.
    # But you can restrict the runs if necessary.
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Make binaries
        uses: sosedoff/actions/golang-build@master
        # Uncomment to following piece to restrict targets
        # with:
        #   args: linux/amd64 darwin/amd64

      - name: Upload build results
        uses: actions/upload-artifact@v1
        with:
          name: sharic_linux_amd64
          path: sharic_linux_amd64
